project_id = "uzsxrvwdfdmucgoshpni"

[functions.verify-api-key]
verify_jwt = true

[functions.verify-exchange-key]
verify_jwt = true

[functions.get-bitget-portfolio]
verify_jwt = true

[functions.mkt-data-agent]
verify_jwt = true

[functions.mkt-data-scheduler]
verify_jwt = false

